// frontend-angular/app/src/app/components/carga-excel/carga-excel.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CargaExcelService } from './carga-excel.service';
import { Area, Tema, DiccionarioCampo } from '../../services/types';
import { ChangeDetectorRef } from '@angular/core';
import { NgZone } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-carga-excel',
  standalone: true,
  templateUrl: './carga-excel.html',
  imports: [CommonModule, FormsModule],
})
export class CargaExcelComponent implements OnInit {
  private service = inject(CargaExcelService);
  private cdr = inject(ChangeDetectorRef);
  private zone = inject(NgZone);

  areas: Area[] = [];
  temas: Tema[] = [];
  diccionario: DiccionarioCampo[] = [];

  idArea: number | null = null;
  idTema: number | null = null;

  archivo: File | null = null;
  mensaje = '';
  isLoading = false;
  progress = 0;

  hojas: string[] = [];
  hojaSeleccionada = '';

  ngOnInit() {
    this.service.getAreas().subscribe({
      next: (data) => {
        // 1. Asignamos los datos
        this.areas = data;
        // 2. Avisamos a Angular que revise la vista inmediatamente
        this.cdr.detectChanges();
        console.log('ÁREAS renderizando:', this.areas);
      },
      error: (error) => {
        this.mensaje = 'Error al cargar áreas';
        this.cdr.detectChanges();
      },
    });
  }

  async onAreaChange(value: string) {
    this.idArea = value ? Number(value) : null;
    this.idTema = null;
    this.archivo = null;
    this.diccionario = [];
    this.mensaje = '';

    if (this.idArea) {
      try {
        this.service.getTemas(this.idArea).subscribe((data) => {
          this.zone.run(() => {
            this.temas = data;
            console.log('Temas cargados:', this.temas);
            this.cdr.detectChanges();
          });
        });
      } catch (error) {
        console.error('Error al cargar temas:', error);
        this.mensaje = 'Error al cargar temas';
        this.cdr.detectChanges();
      }
    } else {
      this.temas = [];
    }
  }

  onTemaChange(value: string) {
    this.idTema = value ? Number(value) : null;

    if (!this.idTema) {
      this.diccionario = [];
      return;
    }

    this.service.getDiccionario(this.idTema).subscribe({
      next: (data) => {
        this.diccionario = data;
        this.cdr.detectChanges();
      },
      error: () => {
        this.mensaje = 'Error al cargar diccionario';
        this.cdr.detectChanges();
      },
    });
  }
  onFileChange(event: any) {
    const file = event.target.files?.[0];
    if (!file) return;

    this.archivo = file;

    this.service.obtenerHojas(file).subscribe({
      next: (data) => {
        this.hojas = data.hojas || [];
        this.cdr.detectChanges();
      },
      error: () => {
        this.mensaje = 'Error al leer hojas';
        this.cdr.detectChanges();
      },
    });
  }

  onSubmit() {
    if (!this.archivo || !this.idTema || !this.idArea) return;

    if (!this.hojaSeleccionada) {
      this.mensaje = 'Seleccione una hoja';
      this.cdr.detectChanges();
      return;
    }

    this.isLoading = true;
    this.progress = 0;

    let value = 0;

    const interval = setInterval(() => {
      value += Math.random() * 15;
      if (value >= 90) value = 90;
      this.progress = Math.floor(value);
      this.cdr.detectChanges();
    }, 300);

    this.service
      .subirExcel(this.idArea, this.idTema, this.archivo, this.hojaSeleccionada)
      .subscribe({
        next: (data) => {
          clearInterval(interval);
          this.progress = 100;
          this.mensaje = `Archivo cargado con ${data.total_registros} registros`;
          this.isLoading = false;
          this.cdr.detectChanges();
        },
        error: (err) => {
          clearInterval(interval);

          console.log('ERROR COMPLETO:', err);

          const errorData = err.error;

          if (errorData?.error === 'Estructura de columnas inválida') {
            const faltantes = errorData.faltantes?.join(', ') || 'Ninguno';
            const extras = errorData.extras?.join(', ') || 'Ninguno';

            this.mensaje = ` Columnas inválidas
          Faltantes: ${faltantes}
          Extras: ${extras}`;
          } else {
            this.mensaje = errorData?.error || 'Error al enviar archivo';
          }

          this.isLoading = false;
          this.cdr.detectChanges();
        },
      });
  }
}

// frontend/src/modules/cargaExcel/CargaExcel.tsx
import React, { useEffect, useState } from "react";
import { Progress } from "antd";
import {
  getAreas,
  getTemas,
  getDiccionario,
  subirExcel,
  obtenerHojas,
} from "./services";
import type { Area, Tema, DiccionarioCampo } from "./types";

const CargaExcel: React.FC = () => {
  const [areas, setAreas] = useState<Area[]>([]);
  const [temas, setTemas] = useState<Tema[]>([]);
  const [diccionario, setDiccionario] = useState<DiccionarioCampo[]>([]);

  const [idArea, setIdArea] = useState<number | "">("");
  const [idTema, setIdTema] = useState<number | "">("");

  const [archivo, setArchivo] = useState<File | null>(null);
  const [mensaje, setMensaje] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [progress, setProgress] = useState(0);
  const [hojas, setHojas] = useState<string[]>([]);
  const [hojaSeleccionada, setHojaSeleccionada] = useState<string>("");

  /* 🔹 Cargar áreas al montar */
  useEffect(() => {
    getAreas().then(setAreas);
  }, []);

  /* 🔹 Cambio de área */
  const onAreaChange = async (value: number | "") => {
    setIdArea(value);
    setIdTema("");
    setArchivo(null);
    setDiccionario([]);
    setMensaje("");

    if (value !== "") {
      const data = await getTemas(value);
      setTemas(data);
    } else {
      setTemas([]);
    }
  };

  /* 🔹 Cambio de tema */
  const onTemaChange = async (value: number | "") => {
    setIdTema(value);
    setArchivo(null);
    setMensaje("");

    if (value !== "") {
      const dic = await getDiccionario(value);
      setDiccionario(dic);
    } else {
      setDiccionario([]);
    }
  };

  /* 🔹 Envío del archivo */
  const onSubmit = () => {
    if (!archivo || !idTema) return;

    setIsLoading(true);
    setProgress(0);

    let value = 0;

    const interval = setInterval(() => {
      value += Math.random() * 15;
      if (value >= 90) value = 90;
      setProgress(Math.floor(value));
    }, 300);

    setTimeout(async () => {
      try {
        if (!hojaSeleccionada) {
          setMensaje("Seleccione una hoja del Excel");
          return;
        }
        const data = await subirExcel(idTema, archivo, hojaSeleccionada);

        clearInterval(interval);
        setProgress(100);

        setMensaje(`Archivo cargado con ${data.total_registros} registros`);
      } catch (err: any) {
        clearInterval(interval);

        if (err?.error === "Errores de validación") {
          const detalles = err.detalle
            ?.slice(0, 5)
            .map((e: any) => `Fila ${e.fila}: ${e.columna} - ${e.error}`)
            .join(" | ");

          setMensaje(`❌ ${err.total_errores} errores. ${detalles}`);
        } else if (err?.error) {
          setMensaje(`❌ ${err.error}`);
        } else {
          setMensaje("❌ Error al enviar el archivo");
        }
      } finally {
        setIsLoading(false);
      }
    }, 0);
  };

  return (
    <div className="container mt-4">
      <h3>Carga de Excel</h3>

      <div className="contenedor-formulario">
        {/* IZQUIERDA */}
        <div className="lado-izquierdo">
          {/* Área */}
          <div className="select-wrapper">
            <select
              className="select-custom"
              value={idArea}
              disabled={isLoading}
              onChange={(e) =>
                onAreaChange(e.target.value ? Number(e.target.value) : "")
              }
            >
              <option value="">Seleccione área</option>
              {areas.map((a) => (
                <option key={a.id_area} value={a.id_area}>
                  {a.nombre}
                </option>
              ))}
            </select>
          </div>

          {/* Tema */}
          <div className="select-wrapper">
            <select
              className="select-custom"
              value={idTema}
              disabled={idArea === "" || isLoading}
              onChange={(e) =>
                onTemaChange(e.target.value ? Number(e.target.value) : "")
              }
            >
              <option value="">Seleccione tema</option>
              {temas.map((t) => (
                <option key={t.id_tema} value={t.id_tema}>
                  {t.nombre}
                </option>
              ))}
            </select>
          </div>

          {/* Archivo */}
          <input
            type="file"
            className="input-custom"
            accept=".xlsx,.xls"
            disabled={idTema === "" || isLoading}
            onChange={async (e) => {
              const file = e.target.files?.[0] || null;
              setArchivo(file);

              if (file) {
                try {
                  console.log("📂 Archivo seleccionado:", file.name);

                  const data = await obtenerHojas(file);

                  console.log("📑 Hojas recibidas:", data);

                  setHojas(data.hojas || []);
                } catch (error) {
                  console.error("❌ Error obteniendo hojas:", error);
                  setMensaje("Error al leer las hojas del Excel");
                }
              }
            }}
          />
          {hojas.length > 0 && (
            <div className="select-wrapper">
              <select
                className="select-custom"
                value={hojaSeleccionada}
                onChange={(e) => setHojaSeleccionada(e.target.value)}
              >
                <option value="">Seleccione hoja</option>
                {hojas.map((h, i) => (
                  <option key={i} value={h}>
                    {h}
                  </option>
                ))}
              </select>
            </div>
          )}
          {/* Botón */}
          <button
            className="btn-custom"
            disabled={idTema === "" || isLoading}
            onClick={onSubmit}
          >
            Subir archivo
          </button>

          {/* Barra de progreso */}
          {isLoading && (
            <div style={{ marginTop: "1rem" }}>
              <p style={{ marginBottom: "0.5rem", fontSize: "0.9rem" }}>
                Procesando...
              </p>

              <Progress
                percent={progress}
                status="active"
                strokeColor="#00acae"
              />
            </div>
          )}

          {/* Mensaje */}
          {mensaje && <div className="bloque-info">{mensaje}</div>}
        </div>

        {/* DERECHA */}
        <div className="lado-derecho">
          {diccionario.length > 0 && (
            <div className="bloque-info">
              <strong>Columnas esperadas:</strong>
              <ul>
                {diccionario.map((c) => (
                  <li key={c.id_campo}>
                    {c.columna_excel}
                    {c.obligatorio && <strong> *</strong>}
                    <small className="text-muted"> ({c.tipo_dato})</small>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CargaExcel;
