// frontend/src/modules/RevisarFicha/RevisarFicha.tsx

import { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Document, Page, pdfjs } from "react-pdf";
import "../../assets/css/estilos.css";

const pdfModules = import.meta.glob("./Fichas_estatales/*.pdf", {
  eager: true,
  import: "default",
}) as Record<string, string>;

const pptModules = import.meta.glob("./Fichas_estatales/*.{ppt,pptx,PPT,PPTX}", {
  eager: true,
  import: "default",
}) as Record<string, string>;

const normalizarClave = (valor: string) =>
  valor
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, "");

const extraerNombreEntidad = (item: unknown): string | null => {
  if (typeof item === "string") {
    const nombre = item.trim();
    return nombre.length > 0 ? nombre : null;
  }

  if (item && typeof item === "object" && "nombre" in item) {
    const nombre = (item as { nombre?: unknown }).nombre;
    if (typeof nombre === "string") {
      const limpio = nombre.trim();
      return limpio.length > 0 ? limpio : null;
    }
  }

  return null;
};

const obtenerPdfPorEntidad = (entidad: string) => {
  if (entidad === "Aguascalientes") return pdfModules["./Fichas_estatales/Ficha_Estatal_AGUASCALIENTES.pdf"] ?? null;
  if (entidad === "Baja California") return pdfModules["./Fichas_estatales/Ficha_Estatal_BAJA CALIFORNIA.pdf"] ?? null;
  if (entidad === "Baja California Sur") return pdfModules["./Fichas_estatales/Ficha_Estatal_BAJA CALIFORNIA SUR.pdf"] ?? null;
  if (entidad === "Campeche") return pdfModules["./Fichas_estatales/Ficha_Estatal_CAMPECHE.pdf"] ?? null;
  if (entidad === "Coahuila") return pdfModules["./Fichas_estatales/Ficha_Estatal_COAHUILA.pdf"] ?? null;
  if (entidad === "Colima") return pdfModules["./Fichas_estatales/Ficha_Estatal_COLIMA.pdf"] ?? null;
  if (entidad === "Chiapas") return pdfModules["./Fichas_estatales/Ficha_Estatal_CHIAPAS.pdf"] ?? null;
  if (entidad === "Chihuahua") return pdfModules["./Fichas_estatales/Ficha_Estatal_CHIHUAHUA.pdf"] ?? null;
  if (entidad === "Ciudad de México") return pdfModules["./Fichas_estatales/Ficha_Estatal_CIUDAD DE MÉXICO.pdf"] ?? null;
  if (entidad === "Durango") return pdfModules["./Fichas_estatales/Ficha_Estatal_DURANGO.pdf"] ?? null;
  if (entidad === "Guanajuato") return pdfModules["./Fichas_estatales/Ficha_Estatal_GUANAJUATO.pdf"] ?? null;
  if (entidad === "Guerrero") return pdfModules["./Fichas_estatales/Ficha_Estatal_GUERRERO.pdf"] ?? null;
  if (entidad === "Hidalgo") return pdfModules["./Fichas_estatales/Ficha_Estatal_HIDALGO.pdf"] ?? null;
  if (entidad === "Jalisco") return pdfModules["./Fichas_estatales/Ficha_Estatal_JALISCO.pdf"] ?? null;
  if (entidad === "Estado de México") return pdfModules["./Fichas_estatales/Ficha_Estatal_ESTADO DE MÉXICO.pdf"] ?? null;
  if (entidad === "Michoacán") return pdfModules["./Fichas_estatales/Ficha_Estatal_MICHOACÁN.pdf"] ?? null;
  if (entidad === "Morelos") return pdfModules["./Fichas_estatales/Ficha_Estatal_MORELOS.pdf"] ?? null;
  if (entidad === "Nayarit") return pdfModules["./Fichas_estatales/Ficha_Estatal_NAYARIT.pdf"] ?? null;
  if (entidad === "Nuevo León") return pdfModules["./Fichas_estatales/Ficha_Estatal_NUEVO LEÓN.pdf"] ?? null;
  if (entidad === "Oaxaca") return pdfModules["./Fichas_estatales/Ficha_Estatal_OAXACA.pdf"] ?? null;
  if (entidad === "Puebla") return pdfModules["./Fichas_estatales/Ficha_Estatal_PUEBLA.pdf"] ?? null;
  if (entidad === "Querétaro") return pdfModules["./Fichas_estatales/Ficha_Estatal_QUERÉTARO.pdf"] ?? null;
  if (entidad === "Quintana Roo") return pdfModules["./Fichas_estatales/Ficha_Estatal_QUINTANA ROO.pdf"] ?? null;
  if (entidad === "San Luis Potosí") return pdfModules["./Fichas_estatales/Ficha_Estatal_SAN LUIS POTOSÍ.pdf"] ?? null;
  if (entidad === "Sinaloa") return pdfModules["./Fichas_estatales/Ficha_Estatal_SINALOA.pdf"] ?? null;
  if (entidad === "Sonora") return pdfModules["./Fichas_estatales/Ficha_Estatal_SONORA.pdf"] ?? null;
  if (entidad === "Tabasco") return pdfModules["./Fichas_estatales/Ficha_Estatal_TABASCO.pdf"] ?? null;
  if (entidad === "Tamaulipas") return pdfModules["./Fichas_estatales/Ficha_Estatal_TAMAULIPAS.pdf"] ?? null;
  if (entidad === "Tlaxcala") return pdfModules["./Fichas_estatales/Ficha_Estatal_TLAXCALA.pdf"] ?? null;
  if (entidad === "Veracruz") return pdfModules["./Fichas_estatales/Ficha_Estatal_VERACRUZ.pdf"] ?? null;
  if (entidad === "Yucatán") return pdfModules["./Fichas_estatales/Ficha_Estatal_YUCATÁN.pdf"] ?? null;
  if (entidad === "Zacatecas") return pdfModules["./Fichas_estatales/Ficha_Estatal_ZACATECAS.pdf"] ?? null;

  // Fallback: busca por coincidencia normalizada para evitar fallos por acentos/encoding.
  const claveEntidad = normalizarClave(entidad);
  const entradaEncontrada = Object.entries(pdfModules).find(([ruta]) => {
    const nombreArchivo = ruta.split("/").pop() ?? "";
    const entidadArchivo = nombreArchivo
      .replace("Ficha_Estatal_", "")
      .replace(".pdf", "");

    return normalizarClave(entidadArchivo) === claveEntidad;
  });

  if (entradaEncontrada) {
    return entradaEncontrada[1];
  }

  return null;
};

const obtenerPptPorEntidad = (entidad: string) => {
  const claveEntidad = normalizarClave(entidad);

  const entradaEncontrada = Object.entries(pptModules).find(([ruta]) => {
    const nombreArchivo = ruta.split("/").pop() ?? "";
    const baseSinExtension = nombreArchivo.replace(/\.(ppt|pptx)$/i, "");
    const baseNormalizada = normalizarClave(baseSinExtension);

    return baseNormalizada.includes(claveEntidad);
  });

  if (entradaEncontrada) {
    return entradaEncontrada[1];
  }

  return null;
};

// Worker de PDF.js
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

const ENTIDADES_FALLBACK = [
  "Aguascalientes","Baja California","Baja California Sur","Campeche","Coahuila","Colima","Chiapas","Chihuahua",
  "Ciudad de México","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","Estado de México","Michoacán","Morelos",
  "Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco",
  "Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"
];

const hospitalesPorEntidad: Record<string, string[]> = {
  Aguascalientes: [], "Baja California": [], "Baja California Sur": [], Campeche: [], Coahuila: [], Colima: [],
  Chiapas: [], Chihuahua: [], "Ciudad de México": [], Durango: [], Guanajuato: [], Guerrero: [], Hidalgo: [],
  Jalisco: [], "Estado de México": [], Michoacán: [], Morelos: [], Nayarit: [], "Nuevo León": [], Oaxaca: [],
  Puebla: [], Querétaro: [], "Quintana Roo": [], "San Luis Potosí": [], Sinaloa: [], Sonora: [], Tabasco: [],
  Tamaulipas: [], Tlaxcala: [], Veracruz: [], Yucatán: [], Zacatecas: [],
};

type TipoFicha = "estatal" | "hospitalaria";
type EstatusRevision = "" | "correcta" | "correccion";

interface RevisionPorPagina {
  estatus: EstatusRevision;
  comentario: string;
}

interface ItemBitacora {
  pagina?: number;
  estatus?: string;
  comentario?: string;
}

const clonarRevisiones = (items: RevisionPorPagina[]) =>
  items.map((item) => ({
    estatus: item.estatus,
    comentario: item.comentario,
  }));

export default function RevisarFicha() {

  const [numPages, setNumPages] = useState(0);
  const [paginaActual, setPaginaActual] = useState(1);
  const [entidadSeleccionada, setEntidadSeleccionada] = useState("Aguascalientes");
  const [entidades, setEntidades] = useState<string[]>(ENTIDADES_FALLBACK);
  const [tipoFicha, setTipoFicha] = useState<TipoFicha>("estatal");
  const [hospitalSeleccionado, setHospitalSeleccionado] = useState("");
  const [revisiones, setRevisiones] = useState<RevisionPorPagina[]>([]);
  const [revisionesBase, setRevisionesBase] = useState<RevisionPorPagina[]>([]);
  const [modalRevision, setModalRevision] = useState<{
    abierto: boolean;
    titulo: string;
    mensaje: string;
    tipo: "info" | "warning" | "success";
  }>({
    abierto: false,
    titulo: "",
    mensaje: "",
    tipo: "info",
  });

  const visorPdfRef = useRef<HTMLDivElement | null>(null);
  const [pdfWidth, setPdfWidth] = useState(900);

  const hospitalesDisponibles = hospitalesPorEntidad[entidadSeleccionada] || [];

  const pdfSeleccionado =
    tipoFicha === "estatal"
      ? obtenerPdfPorEntidad(entidadSeleccionada)
      : null;

  const pptSeleccionado =
    tipoFicha === "estatal"
      ? obtenerPptPorEntidad(entidadSeleccionada)
      : null;

  useEffect(() => {
    let isMounted = true;

    const cargarEntidades = async () => {
      try {
        const res = await fetch("/api/catalogos/entidades/");
        if (!res.ok) return;

        const payload: unknown = await res.json();
        if (!Array.isArray(payload)) return;

        const nombres = payload
          .map(extraerNombreEntidad)
          .filter((nombre): nombre is string => Boolean(nombre));

        if (!isMounted || nombres.length === 0) return;

        setEntidades(nombres);
        setEntidadSeleccionada((prev) =>
          nombres.includes(prev) ? prev : nombres[0],
        );
      } catch {
        // Si falla API, se mantiene el fallback local.
      }
    };

    cargarEntidades();

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {

    const contenedor = visorPdfRef.current;
    if (!contenedor) return;

    const actualizarAncho = () => {
      const anchoDisponible = contenedor.clientWidth;
      const anchoFinal = Math.max(300, anchoDisponible - 24);
      setPdfWidth(anchoFinal);
    };

    actualizarAncho();

    const resizeObserver = new ResizeObserver(() => {
      actualizarAncho();
    });

    resizeObserver.observe(contenedor);
    window.addEventListener("resize", actualizarAncho);

    return () => {
      resizeObserver.disconnect();
      window.removeEventListener("resize", actualizarAncho);
    };

  }, []);

  // #Mario: Inicio helper base de objeto para bitacora.
  const obtenerBaseObjeto = () => {
    const nombrePdf = (pdfSeleccionado?.split("/").pop() ?? `Ficha_Estatal_${entidadSeleccionada}.pdf`)
      .replace(/\?.*$/, "");

    return nombrePdf.replace(/\.pdf$/i, "").replace(/\s+/g, "_");
  };
  // #Mario: Fin helper base de objeto para bitacora.

  // #Mario: Inicio carga de revisiones guardadas por entidad.
  const cargarRevisionesGuardadas = async (totalPaginas: number) => {
    const vacias: RevisionPorPagina[] = Array.from({ length: totalPaginas }, () => ({
      estatus: "",
      comentario: "",
    }));

    if (!pdfSeleccionado || totalPaginas <= 0) {
      setRevisiones(clonarRevisiones(vacias));
      setRevisionesBase(clonarRevisiones(vacias));
      return;
    }

    try {
      const res = await fetch(
        `/api/catalogos/bitacora/?id_presentacion=${encodeURIComponent(tipoFicha)}&id_objeto_base=${encodeURIComponent(obtenerBaseObjeto())}`,
      );

      if (!res.ok) {
        setRevisiones(clonarRevisiones(vacias));
        setRevisionesBase(clonarRevisiones(vacias));
        return;
      }

      const data: unknown = await res.json();
      const items = (data && typeof data === "object" && Array.isArray((data as { items?: unknown }).items)
        ? (data as { items: unknown[] }).items
        : []) as ItemBitacora[];

      for (const item of items) {
        const pagina = Number(item.pagina);
        if (!Number.isInteger(pagina) || pagina < 1 || pagina > totalPaginas) continue;

        const estatusRaw = String(item.estatus || "").trim().toLowerCase();
        const estatus: EstatusRevision =
          estatusRaw === "aprobado"
            ? "correcta"
            : estatusRaw === "requiere corrección" || estatusRaw === "requiere correccion"
            ? "correccion"
            : "";

        vacias[pagina - 1] = {
          estatus,
          comentario: String(item.comentario || ""),
        };
      }

      setRevisiones(clonarRevisiones(vacias));
      setRevisionesBase(clonarRevisiones(vacias));
    } catch {
      setRevisiones(clonarRevisiones(vacias));
      setRevisionesBase(clonarRevisiones(vacias));
    }
  };
  // #Mario: Fin carga de revisiones guardadas por entidad.

  const onDocumentLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
    setPaginaActual(1);

    void cargarRevisionesGuardadas(numPages);
  };

  // #Mario: Inicio manejo de error de carga PDF.
  const onDocumentLoadError = () => {
    setNumPages(0);
    abrirModalRevision(
      "Error al cargar la ficha",
      "No se pudo cargar el PDF seleccionado.",
      "warning",
    );
  };
  // #Mario: Fin manejo de error de carga PDF.

  const siguiente = () => {
    if (paginaActual < numPages) setPaginaActual(paginaActual + 1);
  };

  const anterior = () => {
    if (paginaActual > 1) setPaginaActual(paginaActual - 1);
  };

  const cambiarEstatus = (estatus: EstatusRevision) => {

    const copia = [...revisiones];
    if (!copia[paginaActual - 1]) return;

    copia[paginaActual - 1] = {
      ...copia[paginaActual - 1],
      estatus,
    };

    if (estatus === "correcta") {
      copia[paginaActual - 1] = {
        ...copia[paginaActual - 1],
        comentario: "",
      };
    }

    setRevisiones(copia);
  };

  const cambiarComentario = (texto: string) => {

    const copia = [...revisiones];
    if (!copia[paginaActual - 1]) return;

    copia[paginaActual - 1] = {
      ...copia[paginaActual - 1],
      comentario: texto,
    };
    setRevisiones(copia);
  };

  // #Mario: Inicio helpers de modal de finalizacion.
  const abrirModalRevision = (
    titulo: string,
    mensaje: string,
    tipo: "info" | "warning" | "success" = "info",
  ) => {
    setModalRevision({
      abierto: true,
      titulo,
      mensaje,
      tipo,
    });
  };

  const cerrarModalRevision = () => {
    setModalRevision((prev) => ({
      ...prev,
      abierto: false,
    }));
  };
  // #Mario: Fin helpers de modal de finalizacion.

  // #Mario: Inicio guardado de revision de paginas revisadas.
  const guardarRevisionPagina = async () => {
    if (!pdfSeleccionado) return;

    const revisionesGuardables = revisiones
      .map((revision, index) => ({
        pagina: index + 1,
        revision,
        revisionBase: revisionesBase[index] || { estatus: "", comentario: "" },
      }))
      .filter(({ revision, revisionBase }) => {
        const revisada = revision.estatus === "correcta" || revision.estatus === "correccion";
        if (!revisada) {
          return false;
        }

        return (
          revision.estatus !== revisionBase.estatus ||
          (revision.comentario || "") !== (revisionBase.comentario || "")
        );
      });

    if (revisionesGuardables.length === 0) {
      abrirModalRevision("Sin cambios", "No hay cambios nuevos por guardar.", "info");
      return;
    }

    try {
      for (const { pagina, revision } of revisionesGuardables) {
        const estatusTexto =
          revision.estatus === "correcta"
            ? "Aprobado"
            : "Requiere corrección";

        const payload = {
          id: "010101",
          id_user: "311095917",
          id_presentacion: tipoFicha,
          id_objeto: `${obtenerBaseObjeto()}_${pagina}`,
          comentario: revision.comentario || "",
          estatus: estatusTexto,
        };

        const res = await fetch("/api/catalogos/bitacora/", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(payload),
        });

        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          const message =
            typeof data?.message === "string"
              ? data.message
              : `No se pudo guardar la página ${pagina} en bitácora.`;
          abrirModalRevision("No se pudo guardar", message, "warning");
          return;
        }
      }

      setRevisionesBase(clonarRevisiones(revisiones));

      abrirModalRevision(
        "Guardado exitoso",
        `Se guardaron ${revisionesGuardables.length} páginas modificadas correctamente.`,
        "success",
      );
    } catch {
      abrirModalRevision("Error de conexión", "Error de conexión al guardar la revisión.", "warning");
    }
  };
  // #Mario: Fin guardado de revision de paginas revisadas.

  const descargarPPT = () => {
    if (!pptSeleccionado) return;

    const enlace = document.createElement("a");
    enlace.href = pptSeleccionado;

    const extension = pptSeleccionado.toLowerCase().includes(".pptx")
      ? ".pptx"
      : ".ppt";
    enlace.download = `Ficha_Estatal_${entidadSeleccionada}${extension}`;
    enlace.click();
  };

  // #Mario: Inicio accion finalizar revision.
  const finalizarRevision = async () => {
    if (!pdfSeleccionado || numPages <= 0) {
      abrirModalRevision("Sin ficha cargada", "No hay una ficha cargada para finalizar revisión.", "warning");
      return;
    }

    const paginasFaltantes: number[] = [];

    for (let pagina = 1; pagina <= numPages; pagina += 1) {
      const revisionPagina = revisiones[pagina - 1];
      const revisada =
        revisionPagina?.estatus === "correcta" ||
        revisionPagina?.estatus === "correccion";

      if (!revisada) {
        paginasFaltantes.push(pagina);
      }
    }

    if (paginasFaltantes.length > 0) {
      abrirModalRevision(
        "Páginas pendientes",
        `Faltan por revisar las páginas: ${paginasFaltantes.join(", ")}`,
        "warning",
      );
      return;
    }

    const payload = {
      id_user: "311095917",
      id_presentacion: tipoFicha,
      id_objeto_base: obtenerBaseObjeto(),
      revisiones,
    };

    try {
      const res = await fetch("/api/catalogos/bitacora/reporte-excel/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        const message =
          typeof data?.message === "string"
            ? data.message
            : "No se pudo generar el reporte en Excel.";
        abrirModalRevision("No se pudo finalizar", message, "warning");
        return;
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const enlace = document.createElement("a");
      enlace.href = url;
      enlace.download = `reporte_revision_${obtenerBaseObjeto()}.xls`;
      enlace.click();
      URL.revokeObjectURL(url);

      abrirModalRevision(
        "Revisión finalizada",
        "Todas las páginas están revisadas. Se generó el reporte en Excel.",
        "success",
      );
    } catch {
      abrirModalRevision("Error de conexión", "Error de conexión al generar el reporte en Excel.", "warning");
    }
  };
  // #Mario: Fin accion finalizar revision.

  const revisionActual =
    revisiones[paginaActual - 1] || { estatus: "", comentario: "" };

  // #Mario: Inicio valores visuales del paginador.
  const totalPaginasVisual = Math.max(numPages, revisiones.length, revisionesBase.length);
  const paginaActualVisual =
    pdfSeleccionado && totalPaginasVisual > 0
      ? Math.max(1, Math.min(paginaActual, totalPaginasVisual))
      : 0;
  const paginadorCargando = Boolean(pdfSeleccionado) && totalPaginasVisual === 0;
  // #Mario: Fin valores visuales del paginador.

  // #Mario: Inicio estado visual de revisión por página.
  const paginaRevisada = revisionActual.estatus === "correcta" || revisionActual.estatus === "correccion";
  // #Mario: Fin estado visual de revisión por página.

  const limpiarRevision = () => {
    setPaginaActual(1);
    setNumPages(0);
    setRevisiones([]);
  };

  return (

    <div className="container-fluid py-4">

      <div className="row align-items-start">

        {/* IZQUIERDA */}
        <div className="col-md-6 d-flex flex-column align-items-center ps-5">

          <div className="d-flex justify-content-center gap-4 mb-3">

            <button className="btn-custom" onClick={anterior} disabled={!pdfSeleccionado}>
              <ChevronLeft size={18} className="me-2" />
              Anterior
            </button>

            <button className="btn-custom" onClick={siguiente} disabled={!pdfSeleccionado}>
              Siguiente
              <ChevronRight size={18} className="ms-1" />
            </button>

          </div>

          <div className="visor-pdf" ref={visorPdfRef}>

            {tipoFicha === "hospitalaria" ? (
              <div className="text-center w-100 py-5">
                Seleccione un hospital cuando se cargue el catálogo correspondiente.
              </div>
            ) : pdfSeleccionado ? (

              <Document
                key={`${entidadSeleccionada}-${pdfSeleccionado ?? "sin-pdf"}`}
                file={pdfSeleccionado}
                onLoadSuccess={onDocumentLoadSuccess}
                onLoadError={onDocumentLoadError}
              >

                <Page
                  pageNumber={paginaActual}
                  width={pdfWidth}
                  renderTextLayer={false}
                  renderAnnotationLayer={false}
                />

              </Document>

            ) : (
              <div className="text-center w-100 py-5">
                No se encontró la ficha estatal de la entidad seleccionada.
              </div>
            )}

          </div>

          <div className="mt-3 d-flex justify-content-center align-items-center gap-5 w-100" style={{ maxWidth: "520px" }}>
            <button
              className="btn-custom"
              onClick={descargarPPT}
              disabled={!pptSeleccionado || tipoFicha === "hospitalaria"}
            >
              Descargar
            </button>

            <div className="fw-bold text-white px-3 py-1 rounded" style={{ backgroundColor: "rgba(0, 0, 0, 0.35)" }}>
              {paginadorCargando
                ? "Cargando páginas..."
                : `Página ${paginaActualVisual} de ${totalPaginasVisual}`}
            </div>
          </div>

        </div>

        {/* DERECHA */}
        <div className="col-md-4 d-flex flex-column align-items-center pt-2">

          <div className="w-100" style={{ maxWidth: "420px" }}>

            <div className="mb-4">

              <label className="form-label fw-bold text-white fs-4 text-center d-block">
                Seleccionar Entidad
              </label>

              <div className="select-wrapper">
                <select
                  className="select-custom"
                  value={entidadSeleccionada}
                  onChange={(e) => {
                    setEntidadSeleccionada(e.target.value);
                    setHospitalSeleccionado("");
                    limpiarRevision();
                  }}
                >
                  {entidades.map((entidad) => (
                    <option key={entidad} value={entidad}>
                      {entidad}
                    </option>
                  ))}
                </select>
              </div>

            </div>

            <div className="mb-4">
              <div className="d-flex justify-content-between gap-4">

                <label className="form-check-label text-white fw-semibold text-center flex-fill">
                  <div className="mb-2">Ficha Estatal</div>
                  <input
                    type="radio"
                    name="tipoFicha"
                    className="form-check-input"
                    checked={tipoFicha === "estatal"}
                    onChange={() => {
                      setTipoFicha("estatal");
                      setHospitalSeleccionado("");
                      limpiarRevision();
                    }}
                  />
                </label>

                <label className="form-check-label text-white fw-semibold text-center flex-fill">
                  <div className="mb-2">Ficha Hospitalaria</div>
                  <input
                    type="radio"
                    name="tipoFicha"
                    className="form-check-input"
                    checked={tipoFicha === "hospitalaria"}
                    onChange={() => {
                      setTipoFicha("hospitalaria");
                      limpiarRevision();
                    }}
                  />
                </label>

              </div>
            </div>

            <div className="mb-4">

              <div className="select-wrapper">
                <select
                  className="select-custom"
                  value={hospitalSeleccionado}
                  onChange={(e) => setHospitalSeleccionado(e.target.value)}
                  disabled={tipoFicha !== "hospitalaria"}
                >
                  <option value="">
                    {tipoFicha === "hospitalaria"
                      ? "Seleccione un hospital"
                      : "Disponible al elegir ficha hospitalaria"}
                  </option>
                  {hospitalesDisponibles.map((hospital) => (
                    <option key={hospital} value={hospital}>
                      {hospital}
                    </option>
                  ))}
                </select>
              </div>

            </div>

            <div className="mt-5">

              <label className="form-label fw-bold text-white fs-4 mb-4 text-center d-block">
                Revisión de ficha
              </label>

              <div className="d-flex justify-content-around mb-4">

                <label className="form-check-label text-white fw-semibold text-center">
                  <div className="mb-2">Aprobado</div>
                  <input
                    type="radio"
                    name={`estatus-${paginaActual}`}
                    className="form-check-input"
                    checked={revisionActual.estatus === "correcta"}
                    onChange={() => cambiarEstatus("correcta")}
                    disabled={tipoFicha === "hospitalaria" || !pdfSeleccionado}
                  />
                </label>

                <label className="form-check-label text-white fw-semibold text-center">
                  <div className="mb-2">Requiere corrección</div>
                  <input
                    type="radio"
                    name={`estatus-${paginaActual}`}
                    className="form-check-input"
                    checked={revisionActual.estatus === "correccion"}
                    onChange={() => cambiarEstatus("correccion")}
                    disabled={tipoFicha === "hospitalaria" || !pdfSeleccionado}
                  />
                </label>

              </div>

              <div className="mb-3">

              {/* #Mario: Inicio indicador visual de página revisada. */}
              <div className="d-flex justify-content-between align-items-center mb-3">
                <label className="form-label fw-bold text-white fs-4 mb-0 text-left d-block">
                  Comentarios
                </label>

                <span
                  className={`badge ${paginaRevisada ? "bg-success" : "bg-warning text-dark"}`}
                  style={{ fontSize: "0.9rem" }}
                >
                  {paginaRevisada ? "Página revisada" : "Falta por revisar"}
                </span>
              </div>
              {/* #Mario: Fin indicador visual de página revisada. */}

                <textarea
                  className="input-custom"
                  rows={6}
                  placeholder="Escribe aquí tus comentarios..."
                  disabled={
                    tipoFicha === "hospitalaria" ||
                    !pdfSeleccionado ||
                    revisionActual.estatus !== "correccion"
                  }
                  value={revisionActual.comentario}
                  onChange={(e) => cambiarComentario(e.target.value)}
                  style={{
                    resize: "none",
                    borderRadius: "16px",
                  }}
                />

              </div>

              <div className="d-flex justify-content-center gap-3 mt-4">

                <button
                  className="btn-custom"
                  onClick={guardarRevisionPagina}
                  disabled={tipoFicha === "hospitalaria" || !pdfSeleccionado}
                >
                  Guardar revisión
                </button>

                <button
                  className="btn-custom"
                  onClick={finalizarRevision}
                  disabled={tipoFicha === "hospitalaria" || !pdfSeleccionado}
                >
                  Finalizar revisión
                </button>

              </div>

            </div>

          </div>

        </div>

      </div>

      {modalRevision.abierto && (
        <div className="revision-modal-overlay" onClick={cerrarModalRevision}>
          <div
            className="revision-modal-card"
            onClick={(e) => e.stopPropagation()}
          >
            <div className={`revision-modal-badge revision-modal-${modalRevision.tipo}`}>
              {modalRevision.tipo === "success"
                ? "Completado"
                : modalRevision.tipo === "warning"
                ? "Atención"
                : "Información"}
            </div>

            <h3 className="revision-modal-title">{modalRevision.titulo}</h3>
            <p className="revision-modal-message">{modalRevision.mensaje}</p>

            <div className="d-flex justify-content-center mt-4">
              <button className="btn-custom" onClick={cerrarModalRevision}>
                Cerrar
              </button>
            </div>
          </div>
        </div>
      )}

    </div>

  );
}

// frontend-angular/app/src/app/components/revisar-ficha/revisar-ficha.ts
  // ...existing code...



import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
  OnDestroy,
  OnInit,
  ViewChild,
  inject,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { GlobalWorkerOptions, getDocument, PDFDocumentProxy, RenderTask } from 'pdfjs-dist';

type EstatusRevision = '' | 'correcta' | 'correccion';
interface RevisionPorPagina {
  estatus: EstatusRevision;
  comentario: string;
}

interface EntidadSqlItem {
  cve_edo?: string;
  nombre: string;
}

interface EntidadFichaItem {
  id: string;
  clave: string;
  nombre: string;
  nombre_pdf?: string;
  nombre_ppt?: string;
}

const ENTIDAD_POR_CLAVE: Record<string, string> = {
  AGU: 'Aguascalientes',
  BCN: 'Baja California',
  BCS: 'Baja California Sur',
  CAM: 'Campeche',
  COA: 'Coahuila',
  COL: 'Colima',
  CHP: 'Chiapas',
  CHH: 'Chihuahua',
  CMX: 'Ciudad de Mexico',
  DUR: 'Durango',
  GUA: 'Guanajuato',
  GRO: 'Guerrero',
  HID: 'Hidalgo',
  JAL: 'Jalisco',
  MEX: 'Estado de Mexico',
  MIC: 'Michoacan',
  MOR: 'Morelos',
  NAY: 'Nayarit',
  NLE: 'Nuevo Leon',
  OAX: 'Oaxaca',
  PUE: 'Puebla',
  QUE: 'Queretaro',
  ROO: 'Quintana Roo',
  SLP: 'San Luis Potosi',
  SIN: 'Sinaloa',
  SON: 'Sonora',
  TAB: 'Tabasco',
  TAM: 'Tamaulipas',
  TLA: 'Tlaxcala',
  VER: 'Veracruz',
  YUC: 'Yucatan',
  ZAC: 'Zacatecas',
};

const ORDEN_ENTIDAD_POR_CLAVE: Record<string, string> = {
  AGU: '01',
  BCN: '02',
  BCS: '03',
  CAM: '04',
  COA: '05',
  COL: '06',
  CHP: '07',
  CHH: '08',
  CMX: '09',
  DUR: '10',
  GUA: '11',
  GRO: '12',
  HID: '13',
  JAL: '14',
  MEX: '15',
  MIC: '16',
  MOR: '17',
  NAY: '18',
  NLE: '19',
  OAX: '20',
  PUE: '21',
  QUE: '22',
  ROO: '23',
  SLP: '24',
  SIN: '25',
  SON: '26',
  TAB: '27',
  TAM: '28',
  TLA: '29',
  VER: '30',
  YUC: '31',
  ZAC: '32',
};

const CLAVE_POR_ORDEN_ENTIDAD: Record<string, string> = Object.fromEntries(
  Object.entries(ORDEN_ENTIDAD_POR_CLAVE).map(([clave, orden]) => [orden, clave]),
);

const SUFIJO_FICHAS_ESTATALES = '25_05_2026';
const ARCHIVO_FICHA_NACIONAL_PDF = 'ficha_nacional.pdf';
const ARCHIVO_FICHA_NACIONAL_PPTX = 'FICHA_NACIONAL_14_05_2026.pptx';

interface FichaNacionalArchivos {
  pdf: string | null;
  pptx: string | null;
}

@Component({
  selector: 'app-revisar-ficha',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './revisar-ficha.html',
  styleUrl: './revisar-ficha.css',
})
export class RevisarFichaComponent implements OnInit, AfterViewInit, OnDestroy {
  private readonly cdr = inject(ChangeDetectorRef);
  entidadUsuario = '';

  get soloEntidadUsuario(): boolean {
    return !!this.entidadUsuario && this.entidadUsuario.toLowerCase() !== 'nacional';
  }

  // Mario: fichas locales servidas desde public/fichas.
  private readonly filesApiBase = '/public/fichas';
  private readonly nacionalFilesApiBase = '/public/nacional';

  @ViewChild('visorPdfRef') visorPdfRef?: ElementRef<HTMLElement>;
  @ViewChild('pdfCanvasRef') pdfCanvasRef?: ElementRef<HTMLCanvasElement>;


  constructor(private readonly ngZone: NgZone) {}


  descargarEstatalesZip(): void {
    const url = '/public/fichas/estatales.zip';
    const enlace = document.createElement('a');
    enlace.href = url;
    enlace.download = 'estatales.zip';
    document.body.appendChild(enlace);
    enlace.click();
    document.body.removeChild(enlace);
  }

  entidades: string[] = [];
  entidadesSql: EntidadSqlItem[] = [];
  entidadesConId: EntidadFichaItem[] = [];
  entidadSeleccionada = '';
  tipoFicha: 'estatal' | 'nacional' = 'estatal';
  hospitalSeleccionado = '';
  private hospitales: { id_Unidad: string; Nombre: string; NivelAtencion: string }[] = [];
  numPages = 0;
  paginaActual = 1;
  revisiones: RevisionPorPagina[] = [];
  revisionesBase: RevisionPorPagina[] = [];
  pdfWidth = 900;
  modalRevision = {
    abierto: false,
    titulo: '',
    mensaje: '',
    tipo: 'info' as 'info' | 'warning' | 'success',
  };

  private resizeObserver: ResizeObserver | null = null;
  private intervaloRecarga: number | null = null;
  private pdfDoc: PDFDocumentProxy | null = null;
  private renderTask: RenderTask | null = null;
  private fichaNacionalArchivos: FichaNacionalArchivos = {
    pdf: ARCHIVO_FICHA_NACIONAL_PDF,
    pptx: ARCHIVO_FICHA_NACIONAL_PPTX,
  };

  get hospitalesDisponibles(): { id_Unidad: string; Nombre: string; NivelAtencion: string }[] {
    return this.hospitales;
  }

  get pdfSeleccionado(): string | null {
    if (this.tipoFicha === 'nacional') {
      const archivo = this.fichaNacionalArchivos.pdf?.trim();
      return archivo ? this.construirUrlArchivoNacional(archivo) : null;
    }

    const archivoEntidad = this.entidadSeleccionadaMeta?.nombre_pdf?.trim();
    if (archivoEntidad) return this.construirUrlArchivo(archivoEntidad);

    return null;
  }

  get mostrandoPdf(): boolean {
    return Boolean(this.pdfSeleccionado && this.numPages > 0);
  }

  get pptSeleccionado(): string | null {
    if (this.tipoFicha === 'nacional') {
      const archivo = this.fichaNacionalArchivos.pptx?.trim();
      return archivo ? this.construirUrlArchivoNacional(archivo) : null;
    }

    const archivoEntidad = this.entidadSeleccionadaMeta?.nombre_ppt?.trim();
    if (archivoEntidad) return this.construirUrlArchivo(archivoEntidad);

    return null;
  }

  get revisionActual(): RevisionPorPagina {
    return this.revisiones[this.paginaActual - 1] || { estatus: '', comentario: '' };
  }

  get totalPaginasVisual(): number {
    return Math.max(this.numPages, this.revisiones.length, this.revisionesBase.length);
  }

  get paginaActualVisual(): number {
    if (!this.pdfSeleccionado || this.totalPaginasVisual === 0) return 0;
    return Math.max(1, Math.min(this.paginaActual, this.totalPaginasVisual));
  }

  get paginadorCargando(): boolean {
    return Boolean(this.pdfSeleccionado) && this.totalPaginasVisual === 0;
  }

  get paginaRevisada(): boolean {
    return this.revisionActual.estatus === 'correcta' || this.revisionActual.estatus === 'correccion';
  }

  get modalBadgeTexto(): string {
    if (this.modalRevision.tipo === 'success') return 'Completado';
    if (this.modalRevision.tipo === 'warning') return 'Atencion';
    return 'Informacion';
  }

  get usuarioAutenticado(): string {
    const usuarioLocal = localStorage.getItem('usuarioAutenticado')?.trim() ?? '';
    const usuarioSesion = sessionStorage.getItem('usuario')?.trim() ?? '';
    return usuarioLocal || usuarioSesion || 'sistema';
  }

  get ocultarRevision(): boolean {
    return (localStorage.getItem('statusUsuario') ?? '').trim() === '2';
  }

  private get authHeaders(): HeadersInit {
    return { 'Content-Type': 'application/json' };
  }

  ngOnInit(): void {
    // Mario: ruta de worker acorde a assets del proyecto actual.
    GlobalWorkerOptions.workerSrc = '/assets/pdf.worker.min.mjs';

    const entidad = localStorage.getItem('entidadUsuario');
    this.entidadUsuario = entidad ? entidad : '';

    void this.inicializarCatalogos();
    console.log('[RevisarFicha] ngOnInit llamado');
    console.log('[RevisarFicha] entidades antes:', this.entidades);
    window.addEventListener('resize', this.actualizarAnchoPdfBound);
    this.iniciarRecargaPeriodica();
  }

  private async inicializarCatalogos(): Promise<void> {
    await this.cargarFichaNacionalLocal();
    await this.cargarFichasLocales();
    await this.cargarEntidadesDesdeSql();

    if (this.tipoFicha === 'estatal') {
      await this.cargarPdfActual();
    }
  }

  private async cargarFichaNacionalLocal(): Promise<void> {
    try {
      const response = await fetch('/api/catalogos/ficha-nacional/', {
        cache: 'no-store',
        headers: this.authHeaders,
      });

      if (!response.ok) {
        return;
      }

      const data = (await response.json()) as {
        ok?: boolean;
        pdf?: string | null;
        pptx?: string | null;
      };

      if (!data?.ok) {
        return;
      }

      this.fichaNacionalArchivos = {
        pdf: data.pdf?.trim() || null,
        pptx: data.pptx?.trim() || null,
      };
    } catch {
      // Mario: fallback a nombres por defecto si el endpoint no responde.
    }
  }

  ngAfterViewInit(): void {
    this.resizeObserver = new ResizeObserver(() => this.actualizarAnchoPdf());
    const visor = this.visorPdfRef?.nativeElement;

    if (visor) {
      this.resizeObserver.observe(visor);
      this.actualizarAnchoPdf();
    }

    if (this.pdfDoc) {
      void this.renderizarPaginaActual();
    }
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    window.removeEventListener('resize', this.actualizarAnchoPdfBound);

    if (this.intervaloRecarga !== null) {
      window.clearInterval(this.intervaloRecarga);
    }

    void this.renderTask?.cancel();
    void this.pdfDoc?.destroy();
  }

  seleccionarEntidad(entidad: string): void {
    this.entidadSeleccionada = entidad;
    this.hospitalSeleccionado = '';
    this.limpiarRevision();

    void this.cargarPdfActual();
  }

  seleccionarTipoFicha(tipo: 'estatal' | 'nacional'): void {
    this.tipoFicha = tipo;

    if (tipo === 'estatal') {
      this.hospitalSeleccionado = '';
      this.hospitales = [];
    }

    this.limpiarRevision();

    if (tipo === 'estatal') {
      void this.cargarPdfActual();
    } else {
      void this.cargarPdfActual();
    }
  }

  seleccionarHospital(idUnidad: string): void {
    this.hospitalSeleccionado = idUnidad;
    this.limpiarRevision();
    void this.cargarPdfActual();
  }

  onDocumentLoadError(): void {
    this.numPages = 0;
    this.abrirModal('Error al cargar la ficha', 'No se pudo cargar el PDF seleccionado.', 'warning');
  }

  siguiente(): void {
    if (this.paginaActual < this.numPages) {
      this.paginaActual += 1;
      void this.renderizarPaginaActual();
    }
  }

  anterior(): void {
    if (this.paginaActual > 1) {
      this.paginaActual -= 1;
      void this.renderizarPaginaActual();
    }
  }

  cambiarEstatus(estatus: EstatusRevision): void {
    const idx = this.paginaActual - 1;
    if (!this.revisiones[idx]) return;

    this.revisiones[idx] = {
      ...this.revisiones[idx],
      estatus,
      comentario: estatus === 'correcta' ? '' : this.revisiones[idx].comentario,
    };
  }

  cambiarComentario(texto: string): void {
    const idx = this.paginaActual - 1;
    if (!this.revisiones[idx]) return;

    this.revisiones[idx] = { ...this.revisiones[idx], comentario: texto };
  }

  cerrarModal(): void {
    this.modalRevision.abierto = false;
  }

  async guardarRevision(): Promise<void> {
    if (!this.pdfSeleccionado) {
      this.abrirModal('Sin ficha cargada', 'No hay una ficha cargada para guardar revision.', 'warning');
      return;
    }

    console.log('[RevisarFicha] guardarRevision click', {
      paginaActual: this.paginaActual,
      totalRevisiones: this.revisiones.length,
      baseObjeto: this.obtenerBaseObjeto(),
    });

    const revisadas = this.revisiones
      .map((r, i) => ({ pagina: i + 1, r, base: this.revisionesBase[i] || { estatus: '', comentario: '' } }))
      .filter(({ r }) => r.estatus === 'correcta' || r.estatus === 'correccion');

    if (revisadas.length === 0) {
      this.abrirModal('Sin revision', 'Marca al menos una pagina como Aprobado o Requiere correccion.', 'info');
      return;
    }

    let guardables = revisadas.filter(
      ({ r, base }) =>
        r.estatus !== base.estatus || (r.comentario || '') !== (base.comentario || ''),
    );

    if (guardables.length === 0) {
      guardables = revisadas;
    }

    console.log('[RevisarFicha] paginas a guardar', guardables.map((g) => g.pagina));

    try {
      for (const { pagina, r } of guardables) {
        const random6 = () => Math.floor(100000 + Math.random() * 900000).toString();
        const id = random6();
        const id_bitacora = random6();

        const payload = {
          id,
          id_bitacora,
          id_user: this.usuarioAutenticado,
          id_presentacion: this.tipoFicha,
          id_objeto: `${this.obtenerBaseObjeto()}_${pagina}`,
          comentario: r.comentario || '',
          estatus: r.estatus === 'correcta' ? 'Aprobado' : 'Requiere correccion',
        };

        console.log('[RevisarFicha] POST /bitacora payload', payload);

        const res = await fetch('/api/catalogos/bitacora/', {
          method: 'POST',
          headers: this.authHeaders,
          body: JSON.stringify(payload),
        });

        const respuestaTexto = await res.text();
        console.log('[RevisarFicha] POST /bitacora response', {
          status: res.status,
          ok: res.ok,
          body: respuestaTexto,
        });

        if (!res.ok) {
          this.abrirModal(
            'Error al guardar',
            `No se pudo guardar la pagina ${pagina}. ${respuestaTexto || ''}`.trim(),
            'warning',
          );
          return;
        }
      }

      this.revisionesBase = this.clonarRevisiones(this.revisiones);
      this.abrirModal(
        'Guardado exitoso',
        `Se guardaron ${guardables.length} paginas correctamente.`,
        'success',
      );
    } catch {
      this.abrirModal('Error de conexion', 'Error de conexion al guardar.', 'warning');
    }
  }

  async finalizarRevision(): Promise<void> {
    if (!this.pdfSeleccionado || this.numPages <= 0) {
      this.abrirModal('Sin ficha cargada', 'No hay una ficha cargada.', 'warning');
      return;
    }

    const faltantes = Array.from({ length: this.numPages }, (_, i) => i + 1).filter((p) => {
      const r = this.revisiones[p - 1];
      return !(r?.estatus === 'correcta' || r?.estatus === 'correccion');
    });

    if (faltantes.length > 0) {
      this.abrirModal('Paginas pendientes', `Faltan por revisar: ${faltantes.join(', ')}`, 'warning');
      return;
    }

    try {
      const res = await fetch('/api/catalogos/bitacora/reporte-excel/', {
        method: 'POST',
        headers: this.authHeaders,
        body: JSON.stringify({
          id_user: this.usuarioAutenticado,
          id_presentacion: this.tipoFicha,
          id_objeto_base: this.obtenerBaseObjeto(),
          revisiones: this.revisiones,
        }),
      });

      if (!res.ok) {
        this.abrirModal('Error', 'No se pudo generar el reporte.', 'warning');
        return;
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const enlace = document.createElement('a');
      enlace.href = url;
      enlace.download = `reporte_revision_${this.obtenerBaseObjeto()}.xls`;
      enlace.click();
      URL.revokeObjectURL(url);
      this.abrirModal('Revision finalizada', 'Se genero el reporte en Excel.', 'success');
    } catch {
      this.abrirModal('Error de conexion', 'Error al generar el reporte.', 'warning');
    }
  }

  descargarPpt(): void {
    void this.descargarPptConToken();
  }

  private abrirModal(
    titulo: string,
    mensaje: string,
    tipo: 'info' | 'warning' | 'success' = 'info',
  ): void {
    this.actualizarVista(() => {
      this.modalRevision = { abierto: true, titulo, mensaje, tipo };
    });
  }

  private actualizarVista(callback: () => void): void {
    this.ngZone.run(() => {
      callback();
      this.cdr.detectChanges();
    });
  }

  // Mario: carga de fichas disponibles desde carpeta local (manifest).
  private async cargarFichasLocales(): Promise<void> {
    this.entidadesConId = Object.entries(ENTIDAD_POR_CLAVE)
      .map(([clave, nombre]) => {
        const orden = ORDEN_ENTIDAD_POR_CLAVE[clave];
        return {
          id: orden,
          clave,
          nombre,
          nombre_pdf: this.construirNombreFichaEstatal(orden, clave, '.pdf'),
          nombre_ppt: this.construirNombreFichaEstatal(orden, clave, '.pptx'),
        };
      })
      .filter((item) => Boolean(item.id))
      .sort((a, b) => a.id.localeCompare(b.id));

    console.log('[RevisarFicha] entidadesConId cargadas:', this.entidadesConId.length);
  }

  // Mario: entidades se consumen del backend SQL (cat_entidad) via /api/catalogos/entidades/.
  private async cargarEntidadesDesdeSql(): Promise<void> {
    try {
      const res = await fetch('/api/catalogos/entidades/', { cache: 'no-store' });
      console.log('[RevisarFicha] Endpoint response status:', res.status);
      if (!res.ok) {
        this.ngZone.run(() => {
          this.entidades = [];
          this.entidadSeleccionada = '';
          this.cdr.detectChanges();
        });
        return;
      }

      const payload = (await res.json()) as EntidadSqlItem[];
      console.log('[RevisarFicha] Payload SQL recibido:', payload.length, payload.slice(0, 3));
      const entidadesSql = Array.isArray(payload)
        ? payload.filter((item) => String(item?.nombre ?? '').trim().length > 0)
        : [];

      const disponiblesPorClave = new Set(this.entidadesConId.map((item) => item.clave));
      const disponiblesPorNombre = new Map(
        this.entidadesConId.map((item) => [this.normalizarTexto(item.nombre), item]),
      );

      let entidadesDisponibles = entidadesSql.filter((item) => {
        const clave = String(item?.cve_edo ?? '')
          .trim()
          .toUpperCase();

        if (clave) {
          return disponiblesPorClave.has(clave);
        }

        return disponiblesPorNombre.has(this.normalizarTexto(item.nombre));
      });

      if (entidadesDisponibles.length === 0) {
        entidadesDisponibles = entidadesSql.length > 0
          ? [...entidadesSql]
          : this.entidadesConId.map((item) => ({ cve_edo: item.clave, nombre: item.nombre }));
      }

      if (this.soloEntidadUsuario) {
        const entidadNormalizada = this.normalizarTexto(this.entidadUsuario);
        entidadesDisponibles = entidadesDisponibles.filter(
          (item) => this.normalizarTexto(item.nombre) === entidadNormalizada,
        );
      }

      this.ngZone.run(() => {
        this.entidadesSql = entidadesDisponibles;
        this.entidades = entidadesDisponibles.map((item) => item.nombre);
        console.log(
          '[RevisarFicha] Entidades disponibles para combo:',
          this.entidades.length,
          this.entidades.slice(0, 3),
        );
        this.entidadSeleccionada = this.entidades[0] ?? '';
        this.cdr.detectChanges();
      });
    } catch {
      this.ngZone.run(() => {
        this.entidadesSql = [];
        this.entidades = [];
        this.entidadSeleccionada = '';
        this.cdr.detectChanges();
      });
      console.error('[RevisarFicha] Error cargando entidades SQL');
    }
  }

  private normalizarTexto(valor: string): string {
    return valor
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .trim();
  }

  private get entidadIdSeleccionada(): string {
    return this.entidadSeleccionadaMeta?.id ?? '';
  }

  private get entidadSqlSeleccionada(): EntidadSqlItem | null {
    const seleccion = this.normalizarTexto(this.entidadSeleccionada);
    return this.entidadesSql.find((item) => this.normalizarTexto(item.nombre) === seleccion) ?? null;
  }

  private get entidadSeleccionadaMeta(): EntidadFichaItem | null {
    const cveEdo = String(this.entidadSqlSeleccionada?.cve_edo ?? '')
      .trim()
      .toUpperCase();

    const clave = CLAVE_POR_ORDEN_ENTIDAD[cveEdo] ?? cveEdo;

    if (clave) {
      return this.entidadesConId.find((item) => item.clave === clave) ?? null;
    }

    const seleccion = this.normalizarTexto(this.entidadSeleccionada);
    return this.entidadesConId.find((item) => this.normalizarTexto(item.nombre) === seleccion) ?? null;
  }

  private construirNombreFichaEstatal(
    orden: string,
    clave: string,
    extension: '.pdf' | '.pptx',
  ): string {
    return `FE_${orden}_${clave}_${SUFIJO_FICHAS_ESTATALES}${extension}`;
  }

  private async cargarHospitales(): Promise<void> {
    // Mario: esta pantalla usa solo fichas locales estatales.
    this.hospitales = [];
  }

  private async cargarRevisionesGuardadas(totalPaginas: number): Promise<void> {
    const vacias: RevisionPorPagina[] = Array.from({ length: totalPaginas }, () => ({
      estatus: '',
      comentario: '',
    }));

    if (!this.pdfSeleccionado || totalPaginas <= 0) {
      this.actualizarVista(() => {
        this.revisiones = this.clonarRevisiones(vacias);
        this.revisionesBase = this.clonarRevisiones(vacias);
      });
      return;
    }

    try {
      const res = await fetch(
        `/api/catalogos/bitacora/?id_user=${encodeURIComponent(this.usuarioAutenticado)}&id_presentacion=${encodeURIComponent(this.tipoFicha)}&id_objeto_base=${encodeURIComponent(this.obtenerBaseObjeto())}`,
        { cache: 'no-store', headers: this.authHeaders },
      );

      if (!res.ok) {
        this.actualizarVista(() => {
          this.revisiones = this.clonarRevisiones(vacias);
          this.revisionesBase = this.clonarRevisiones(vacias);
        });
        return;
      }

      const data: unknown = await res.json();
      const items =
        data && typeof data === 'object' && Array.isArray((data as { items?: unknown[] }).items)
          ? (data as { items: Array<{ pagina?: number; estatus?: string; comentario?: string }> }).items
          : [];

      for (const item of items) {
        const pagina = Number(item.pagina);
        if (!Number.isInteger(pagina) || pagina < 1 || pagina > totalPaginas) continue;

        const estatusRaw = String(item.estatus || '').trim().toLowerCase();
        vacias[pagina - 1] = {
          estatus:
            estatusRaw === 'aprobado'
              ? 'correcta'
              : estatusRaw.includes('correcci')
                ? 'correccion'
                : '',
          comentario: String(item.comentario || ''),
        };
      }

      this.actualizarVista(() => {
        this.revisiones = this.clonarRevisiones(vacias);
        this.revisionesBase = this.clonarRevisiones(vacias);
      });
    } catch {
      this.actualizarVista(() => {
        this.revisiones = this.clonarRevisiones(vacias);
        this.revisionesBase = this.clonarRevisiones(vacias);
      });
    }
  }

  private obtenerBaseObjeto(): string {
    const nombrePdf =
      this.tipoFicha === 'nacional'
        ? (this.fichaNacionalArchivos.pdf?.trim() || ARCHIVO_FICHA_NACIONAL_PDF)
        : (this.entidadSeleccionadaMeta?.nombre_pdf?.trim() ||
          `Ficha_Estatal_${this.entidadSeleccionada}.pdf`);

    return nombrePdf.replace(/\.pdf$/i, '').replace(/\s+/g, '_');
  }

  private obtenerArchivoHospital(extension: '.pdf' | '.pptx'): string | null {
    const idUnidad = this.hospitalSeleccionado.trim();
    if (!idUnidad) return null;
    return `${idUnidad}${extension}`;
  }

  private construirUrlArchivo(nombreArchivo: string): string {
    return `${this.filesApiBase}/${encodeURIComponent(nombreArchivo)}`;
  }

  private construirUrlArchivoNacional(nombreArchivo: string): string {
    return `${this.nacionalFilesApiBase}/${encodeURIComponent(nombreArchivo)}`;
  }

  private limpiarRevision(): void {
    this.actualizarVista(() => {
      this.paginaActual = 1;
      this.numPages = 0;
      this.revisiones = [];
      this.revisionesBase = [];
    });
  }

  private hayCambiosLocales(): boolean {
    return this.revisiones.some((r, i) => {
      const b = this.revisionesBase[i] || { estatus: '', comentario: '' };
      return r.estatus !== b.estatus || (r.comentario || '') !== (b.comentario || '');
    });
  }

  private iniciarRecargaPeriodica(): void {
    if (this.intervaloRecarga !== null) window.clearInterval(this.intervaloRecarga);

    this.intervaloRecarga = window.setInterval(() => {
      if (!this.pdfSeleccionado || this.numPages <= 0 || this.hayCambiosLocales()) {
        return;
      }
      void this.cargarRevisionesGuardadas(this.numPages);
    }, 3000);
  }

  private clonarRevisiones(items: RevisionPorPagina[]): RevisionPorPagina[] {
    return items.map((item) => ({ estatus: item.estatus, comentario: item.comentario }));
  }

  private readonly actualizarAnchoPdfBound = (): void => {
    this.actualizarAnchoPdf();
  };

  private actualizarAnchoPdf(): void {
    const c = this.visorPdfRef?.nativeElement ?? null;
    if (!c) return;

    this.pdfWidth = Math.max(220, Math.min(504, c.clientWidth - 16));
    void this.renderizarPaginaActual();
  }

  private async cargarPdfActual(): Promise<void> {
    const rutaPdf = this.pdfSeleccionado;

    if (!rutaPdf) {
      await this.liberarDocumentoPdf();
      return;
    }

    try {
      await this.liberarDocumentoPdf();
      const response = await fetch(rutaPdf, { headers: this.authHeaders });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const pdfBlob = await response.blob();
      const arrayBuffer = await pdfBlob.arrayBuffer();
      const loadingTask = getDocument({
        data: new Uint8Array(arrayBuffer),
        disableWorker: true,
      } as any);

      this.pdfDoc = await loadingTask.promise;

      this.actualizarVista(() => {
        this.numPages = this.pdfDoc?.numPages ?? 0;
        this.paginaActual = 1;
      });

      await this.cargarRevisionesGuardadas(this.numPages);
      await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
      await this.renderizarPaginaActual();
    } catch {
      await this.liberarDocumentoPdf();
      this.ngZone.run(() => this.onDocumentLoadError());
    }
  }

  private async renderizarPaginaActual(): Promise<void> {
    if (
      !this.pdfDoc ||
      !this.pdfCanvasRef?.nativeElement ||
      this.paginaActual < 1 ||
      this.paginaActual > this.numPages
    ) {
      return;
    }

    try {
      const pagina = await this.pdfDoc.getPage(this.paginaActual);
      const viewportBase = pagina.getViewport({ scale: 1 });
      const anchoDisponible = Math.max(220, this.pdfWidth);
      const escala = anchoDisponible / viewportBase.width;
      const viewport = pagina.getViewport({ scale: Math.max(0.25, escala) });
      const canvas = this.pdfCanvasRef.nativeElement;
      const context = canvas.getContext('2d');

      if (!context) {
        return;
      }

      canvas.width = Math.floor(viewport.width);
      canvas.height = Math.floor(viewport.height);
      canvas.style.width = `${Math.floor(viewport.width)}px`;
      canvas.style.height = `${Math.floor(viewport.height)}px`;

      if (this.renderTask) {
        await this.renderTask.cancel();
        this.renderTask = null;
      }

      context.clearRect(0, 0, canvas.width, canvas.height);

      this.renderTask = pagina.render({ canvasContext: context, viewport, canvas });
      await this.renderTask.promise;
      this.renderTask = null;
    } catch (error) {
      if (!(error instanceof Error) || error.name !== 'RenderingCancelledException') {
        this.onDocumentLoadError();
      }
    }
  }

  private async liberarDocumentoPdf(): Promise<void> {
    if (this.renderTask) {
      await this.renderTask.cancel();
      this.renderTask = null;
    }

    if (this.pdfDoc) {
      await this.pdfDoc.destroy();
      this.pdfDoc = null;
    }

    const canvas = this.pdfCanvasRef?.nativeElement;
    const context = canvas?.getContext('2d');

    if (canvas && context) {
      context.clearRect(0, 0, canvas.width, canvas.height);
      canvas.width = 0;
      canvas.height = 0;
    }
  }

  private async descargarPptConToken(): Promise<void> {
    if (!this.pptSeleccionado) return;

    try {
      const response = await fetch(this.pptSeleccionado, { headers: this.authHeaders });

      if (!response.ok) {
        this.abrirModal('Error al descargar', 'No se pudo descargar la ficha PPT.', 'warning');
        return;
      }

      const extension = this.pptSeleccionado.toLowerCase().includes('.pptx') ? '.pptx' : '.ppt';
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const enlace = document.createElement('a');
      enlace.href = url;
      enlace.download =
        this.tipoFicha === 'nacional'
          ? `Ficha_Nacional${extension}`
          : `Ficha_Estatal_${this.entidadSeleccionada}${extension}`;
      enlace.click();
      URL.revokeObjectURL(url);
    } catch {
      this.abrirModal('Error de conexion', 'Error al descargar la ficha PPT.', 'warning');
    }
  }
}
